### ISSUE TITLE
[PE-D][Tester D] The Info Card Does Not Resize

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-1/tp#166] opened 2023-03-31 17:31 UTC
The info card doesn't resize automatically along with the input. For example, a user have a long name, then the UI is not able to show the full name. Additionally, there is no scroll bar to navigate. Or when you link multipule person into a location, it will not show a list of names.

Follow up explaination : when there is a verticle scroll bar in prescence, it might happen that the horizontal scroll bar cannot be seen if one of the five sections saved many data.

![Resize.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/caa2375b-11c0-408b-8390-abc2b38125cd.png)

![Person_Card_Not_Resized.png](https://raw.githubusercontent.com/chen-jerry-junior/ped/main/files/561e6ef7-9a87-444c-a73c-ac80bedd6972.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chen-jerry-junior/ped#3

**Comment by wxxedu** [comment] 2023-04-05 06:23
Not a bug and won't fix.

**Closed by wxxedu** 2023-04-05 06:23 UTC
