### ISSUE TITLE
equivalence partitioning testing

### ISSUE THREAD

**Issue by BoAi01** [AY2223S2-CS2103T-W11-1/tp#127] opened 2023-03-26 02:07 UTC
Here is one slide from the 24 Mar lecture. It is an example of equivariance partitioning and I think the instance here is closely connected to our program: what if the user enters something like 
```
add sdfs/sddffs some random stuff sdf/name / /name name
```
I am not sure if our current parser can deal with such weird strings nicely. When we design and write test cases, we should probably consider such corner cases. 

By the way, during PE, we can test others' products in this way as well.  :)

![Screenshot 2023-03-26 at 10 03 00 AM](https://user-images.githubusercontent.com/53465243/227751247-15473869-e826-419c-8632-a3204f29d28e.png)

**Comment by wxxedu** [comment] 2023-03-26 08:08
duplicate of #59, but more detailed.

**Closed** 2023-04-09 12:20 UTC
Labels: documentation, enhancement
