### ISSUE TITLE
[PE-D][Tester F] Linkpilot can only link one of /pm and /pf at a time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-1/tp#194] opened 2023-03-31 19:43 UTC
Steps:

1. Create two pilots.
2. Create one flight.
3. Link the two pilots to the flight as Pilot Monitoring and Pilot Flying, e.g. `linkflight /fl 1 /pm 1 /pf 2`

Actual:

The flight is only linked to the `/pf` pilot. Linking to the `/pm` pilot required another command, e.g. `linkflight /fl 1 /pm 1`

Expected:

Both pilots should be linked to the flight appropriately.

Note:

Similar to the `linklocation` issue #3. In general, something to this effect seems to occur for most commands taking multiple arguments of the same type.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jefrai/ped#10

**Comment by wxxedu** [comment] 2023-04-05 06:19
Not a bug/feature flaw. If there are other more important issues, we can choose to leave this out. We may want to be clearer on the DG for this though.

**Comment by wxxedu** [comment] 2023-04-06 01:27
Should be fixed with #239

**Closed by wxxedu** 2023-04-06 01:27 UTC
Labels: documentation
